version: "3.9"

services:
  api:
    image: "api:1.2"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    environment:
      - MONGO_CONNECTION=mongodb://mongodb:27017
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__DatabaseName=ChatBotConversations
      - MongoDB__CollectionName=Conversation
    networks:
      - app-network
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    healthcheck:
      test: [ "CMD", "mongo", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
        - "27017:27017"
    volumes:
        - mongo-data:/data/db
    networks:
        - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
